### ISSUE TITLE
Issues with gnome music

### ISSUE THREAD

**Issue by mortalsdemise13** [linuxmint/linuxmint#160]
after installation trying to launch gnome music fails on mint 19.+ though the flatpak version does load but will not work due to the tracker version being outdated, it says it needs version 2.2.0 or higher.

**Comment by xenopeek** [comment]
This is the error gnome-music gives when launched:
```Original exception was:
Traceback (most recent call last):
  File "/usr/bin/gnome-music", line 142, in <module>
    sys.exit(main())
  File "/usr/bin/gnome-music", line 137, in main
    return run_application()
  File "/usr/bin/gnome-music", line 123, in run_application
    from gnomemusic.application import Application
  File "/usr/lib/python3/dist-packages/gnomemusic/application.py", line 40, in <module>
    from gnomemusic.mpris import MediaPlayer2Service
  File "/usr/lib/python3/dist-packages/gnomemusic/mpris.py", line 28, in <module>
    from gnomemusic.player import PlaybackStatus, RepeatType
  File "/usr/lib/python3/dist-packages/gnomemusic/player.py", line 53, in <module>
    from gnomemusic.scrobbler import LastFmScrobbler
  File "/usr/lib/python3/dist-packages/gnomemusic/scrobbler.py", line 31, in <module>
    gi.require_version('Goa', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Goa not available
```
Installing gir1.2-goa-1.0 fixes this missing dependency problem. Install it through Synaptic or command line with `apt install gir1.2-goa-1.0`.

I think this stems from this packaging bug in Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=899117. It was fixed after Ubuntu LTS 18.04 was released and apparently the packaging bug wasn't fixed afterwards in Ubuntu LTS 18.04 and hence not on Linux Mint 19.x. It should be fixed on Linux Mint 20.

Workaround as above to install the package gir1.2-goa-1.0 which should have been a dependency of gnome-music package.
