### ISSUE TITLE
mintupgrade check only works once

### ISSUE THREAD

**Issue by zolstarym** [linuxmint/linuxmint#274]
On 19.3, running mintupgrade check works as expected the first time, but if it is used a second time, this error occurs:

Traceback (most recent call last):
  File "/usr/bin/mintupgrade", line 620, in <module>
    upgrader = MintUpgrade(command)
  File "/usr/bin/mintupgrade", line 152, in __init__
    with open("/etc/apt/sources.list.d/official-package-repositories.list") as sources:
PermissionError: [Errno 13] Permission denied: '/etc/apt/sources.list.d/official-package-repositories.list'

**Comment by clefebvre** [comment]
Did you change your home dir umask? I can't reproduce this here.

**Comment by zolstarym** [comment]
I don't remember if I changed it or not.
$ umask
0027
and then if I make a file in my home dir:
touch file gives
-rw-r-----  
as default

**Comment by mtwebster** [comment]
That is strict - it must have been changed.  We'll have to make sure to catch that.

In the meantime, try:
```
sudo chmod 644 /etc/fstab
sudo chmod 644 /etc/crypttab (this will fail if you're not using any encryption - that's fine)
```
This should allow you to re-run the upgrade

**Comment by zolstarym** [comment]
I did a chmod go+rw on the official-package-repositories.list file after each mintupgrade command and that worked. Nothing else during the upgrade seemed to break from the non default umask.
