### ISSUE TITLE
linux mint bug my desktop and laptop 

### ISSUE THREAD

**Issue by freddylupin** [linuxmint/linuxmint#297]
===================================================================
 Info                                                              
===================================================================
           PID: 1198 (csd-automount)
           UID: 1000 (snowden)
           GID: 1000 (snowden)
        Signal: 11 (SEGV)
     Timestamp: Sat 2020-09-12 16:26:39 EEST (5 days ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (snowden)
       Boot ID: 25ecb0bff89a4ff9b29dd105090f6a66
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: snowden-HP-Compaq-6000-Pro-MT-PC
       Storage: /var/lib/systemd/coredump/core.csd-automount.1000.25ecb0bff89a4ff9b29dd105090f6a66.1198.1599917199000000000000.lz4
       Message: Process 1198 (csd-automount) of user 1000 dumped core.
                
                Stack trace of thread 1198:
                #0  0x0000563c139c5430 n/a (csd-automount + 0x6430)
                #1  0x00007f65009e8a28 n/a (libglib-2.0.so.0 + 0x52a28)
                #2  0x00007f65009e7e8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                #3  0x00007f65009e8240 n/a (libglib-2.0.so.0 + 0x52240)
                #4  0x00007f65009e8533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #5  0x00007f650107d37d gtk_main (libgtk-3.so.0 + 0x24e37d)
                #6  0x0000563c139c4947 n/a (csd-automount + 0x5947)
                #7  0x00007f650068e0b3 __libc_start_main (libc.so.6 + 0x270b3)
                #8  0x0000563c139c4aae n/a (csd-automount + 0x5aae)
                
                Stack trace of thread 1214:
                #0  0x00007f650077c96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f65009e81ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f65009e82e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f65009e8331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007f6500a11931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f64ffec6609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f6500789103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1217:
                #0  0x00007f650077c96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f65009e81ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f65009e8533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f6500c3feda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007f6500a11931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f64ffec6609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f6500789103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1272:
                #0  0x00007f650077c96f __GI___poll (libc.so.6 + 0x11596f)
                #1  0x00007f65009e81ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f65009e82e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f64fdd4e99d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007f6500a11931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f64ffec6609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f6500789103 __clone (libc.so.6 + 0x122103)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1198]
[New LWP 1214]
[New LWP 1217]
[New LWP 1272]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563c139c5430 in ?? ()
[Current thread is 1 (Thread 0x7f64ff5f0a80 (LWP 1198))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1198]
[New LWP 1214]
[New LWP 1217]
[New LWP 1272]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563c139c5430 in ?? ()
[Current thread is 1 (Thread 0x7f64ff5f0a80 (LWP 1198))]
#0  0x0000563c139c5430 in ?? ()
#1  0x00007f65009e8a28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f65009e7e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f65009e8240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f65009e8533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f650107d37d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x0000563c139c4947 in ?? ()
#7  0x00007f650068e0b3 in __libc_start_main (main=0x563c139c4770, argc=1, argv=0x7ffdda83ee88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdda83ee78) at ../csu/libc-start.c:308
#8  0x0000563c139c4aae in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1198]
[New LWP 1214]
[New LWP 1217]
[New LWP 1272]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563c139c5430 in ?? ()
[Current thread is 1 (Thread 0x7f64ff5f0a80 (LWP 1198))]

Thread 4 (Thread 0x7f64fdd3a700 (LWP 1272)):
#0  0x00007f650077c96f in __GI___poll (fds=0x563c1425c560, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f65009e81ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f65009e82e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f64fdd4e99d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f6500a11931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f64ffec6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140071731963648, -7564013815811065042, 140728269531038, 140728269531039, 140728269531184, 140071731960960, 7624244686037662510, 7624249310695996206}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f6500789103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f64fe59e700 (LWP 1217)):
#0  0x00007f650077c96f in __GI___poll (fds=0x563c1424db40, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f65009e81ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f65009e8533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f6500c3feda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f6500a11931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f64ffec6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140071740761856, -7564013815811065042, 140728269531966, 140728269531967, 140728269532112, 140071740759168, 7624248033964669742, 7624249310695996206}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f6500789103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f64fedaf700 (LWP 1214)):
#0  0x00007f650077c96f in __GI___poll (fds=0x563c1423d240, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f65009e81ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f65009e82e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f65009e8331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f6500a11931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f64ffec6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140071749220096, -7564013815811065042, 140728269531534, 140728269531535, 140728269531680, 140071749217408, 7624246961833458478, 7624249310695996206}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f6500789103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f64ff5f0a80 (LWP 1198)):
#0  0x0000563c139c5430 in ?? ()
No symbol table info available.
#1  0x00007f65009e8a28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f65009e7e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f65009e8240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f65009e8533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f650107d37d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#6  0x0000563c139c4947 in ?? ()
No symbol table info available.
#7  0x00007f650068e0b3 in __libc_start_main (main=0x563c139c4770, argc=1, argv=0x7ffdda83ee88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdda83ee78) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94816027048592, -7564013815811065042, 94816027036288, 140728269532800, 0, 0, 7565075978866604846, 7623812774608583470}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffdda83ee88}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#8  0x0000563c139c4aae in ?? ()
No symbol table info available.
#0  0x0000563c139c5430 in ?? ()
#1  0x00007f65009e8a28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f65009e7e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f65009e8240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f65009e8533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f650107d37d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x0000563c139c4947 in ?? ()
#7  0x00007f650068e0b3 in __libc_start_main (main=0x563c139c4770, argc=1, argv=0x7ffdda83ee88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdda83ee78) at ../csu/libc-start.c:308
#8  0x0000563c139c4aae in ?? ()

**Comment by xenopeek** [comment]
Hi, if you need help with troubleshooting please add some more information. Like your Linux Mint version and when this segfault happens. I assume it happens when you connect some storage device? Please add some details.
