### ISSUE TITLE
Ubiquity: Crash on non-Unicode characters in SSD Name

### ISSUE THREAD

**Issue by DG0lden** [linuxmint/linuxmint#320]
Ubiquity installer from LiveCD (actually USB) crashes on a step after choosing Language, Keyboard Layout and Wi-Fi network:

![screeenshot](https://forums.linuxmint.com/download/file.php?id=64457&mode=view)

Error message in text:
```
Traceback (most recent call last):
  File "/usr/lib/ubiquity/ubiquity/frontend/gtk_ui.py", line 843, in <lambda>
    lambda: self.dbfilter.start(auto_process=True))
  File "/usr/lib/ubiquity/ubiquity/filteredcommand.py", line 103, in start
    prep = self.prepare()
  File "/usr/lib/ubiquity/plugins/ubi-prepare.py", line 478, in prepare
    self.setup_sufficient_space()
  File "/usr/lib/ubiquity/plugins/ubi-prepare.py", line 503, in setup_sufficient_space
    free = self.free_space()
  File "/usr/lib/ubiquity/plugins/ubi-prepare.py", line 517, in free_space
    devices = proc.communicate()[0].rstrip('\n').split('\n')
  File "/usr/lib/python3.8/subprocess.py", line 1011, in communicate
    stdout = self.stdout.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 89: invalid start byte
```

The problem is reproducible with Mint 20 Cinnamon, Mint 20 Mate, Ubuntu 20.04 Desktop and Ubuntu 20.10 Desktop.

My assumption is that the problem lies in the name of SSD "Innovation??IT" where ?? are two strange characters, not readable in console. 
F.i. parted shows it like this:
```
mint@mint:~$ cat /proc/mdstat
Personalities : 
unused devices: <none>
mint@mint:~$ sudo parted -l
Warning: The driver descriptor says the physical block size is 2048 bytes, but
Linux says it is 512 bytes.
Ignore/Cancel? c                                                          
Model: SanDisk Ultra USB 3.0 (scsi)
Disk /dev/sda: 123GB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags: 

Model: INNOVATION��IT (nvme)
Disk /dev/nvme0n1: 1024GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system     Name                          Flags
 1      1049kB  945MB   944MB   ntfs            Basic data partition          hidden, diag
 2      945MB   1217MB  273MB   fat32           EFI system partition          boot, esp
 3      1217MB  1352MB  134MB                   Microsoft reserved partition  msftres
 4      1352MB  382GB   381GB   ntfs            Basic data partition          msftdata
 6      382GB   416GB   33.6GB  linux-swap(v1)                                swap
 7      416GB   1012GB  596GB   ext4
 5      1012GB  1024GB  12.6GB  ntfs            Basic data partition          hidden, diag

```

INXI:
```
mint@mint:~$ inxi -Fxz
System:    Kernel: 5.4.0-26-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: MATE 1.24.0 Distro: Linux Mint 20 Ulyana 
           base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: LENOVO product: 20L6S0AF00 v: ThinkPad T480 serial: <filter> 
           Mobo: LENOVO model: 20L6S0AF00 v: SDK0J40697 WIN serial: <filter> UEFI [Legacy]: LENOVO v: N24ET48W (1.23 ) 
           date: 02/20/2019 
Battery:   ID-1: BAT0 charge: 1.3 Wh condition: 23.9/23.9 Wh (100%) model: LGC 01AV489 status: Unknown 
           ID-2: BAT1 charge: 8.1 Wh condition: 22.8/24.1 Wh (95%) model: Celxpert 01AV424 status: Discharging 
CPU:       Topology: Dual Core model: Intel Core i5-7300U bits: 64 type: MT MCP arch: Amber Lake rev: 9 L2 cache: 3072 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 21599 
           Speed: 700 MHz min/max: 400/3500 MHz Core speeds (MHz): 1: 700 2: 700 3: 701 4: 700 
Graphics:  Device-1: Intel HD Graphics 620 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 20.0.4 direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Lenovo ThinkPad T480 driver: snd_hda_intel v: kernel 
           bus ID: 00:1f.3 
           Sound Server: ALSA v: k5.4.0-26-generic 
Network:   Device-1: Intel Ethernet I219-LM vendor: Lenovo driver: e1000e v: 3.2.6-k port: efa0 bus ID: 00:1f.6 
           IF: enp0s31f6 state: down mac: <filter> 
           Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi v: kernel port: efa0 bus ID: 03:00.0 
           IF: wlp3s0 state: up mac: <filter> 
Drives:    Local Storage: total: 1.04 TiB used: 198.7 MiB (0.0%) 
           ID-1: /dev/nvme0n1 vendor: Innovation model: IT size: 953.87 GiB 
           ID-2: /dev/sda type: USB vendor: SanDisk model: Ultra USB 3.0 size: 114.56 GiB 
Partition: ID-1: / size: 7.58 GiB used: 138.0 MiB (1.8%) fs: overlay source: ERR-102 
           ID-2: /var/log size: 110.38 GiB used: 60.7 MiB (0.1%) fs: ext4 dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 30.0 C mobo: N/A 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 191 Uptime: 21m Memory: 15.16 GiB used: 734.7 MiB (4.7%) Init: systemd runlevel: 5 Compilers: gcc: 9.3.0 
           Shell: bash v: 5.0.16 inxi: 3.0.38 
```

The problem was already reported at Linuxmint forums two times before:

- [MATE Python install error](https://forums.linuxmint.com/viewtopic.php?t=249282)
- [Linux Mint 19.3 and 20 Mate installation error](https://forums.linuxmint.com/viewtopic.php?f=46&t=331895)

**Comment by eipaosxs** [comment]
This is sadly [still happening](https://forums.linuxmint.com/viewtopic.php?f=46&t=341722).

**Comment by DG0lden** [comment]
Close this issue in order to follow it in proper repository: https://github.com/linuxmint/ubiquity/issues/62
