### ISSUE TITLE
Firefox apt source package fails to recompile due to a debian/rules distro version check

### ISSUE THREAD

**Issue by GrapeBacon** [linuxmint/linuxmint#423]
I was attempting to recompile Firefox from the Linux Mint provided source package and notice, without any modification, that it would fail trying to find "usr.bin.firefox.in" every time. However, it would compile just fine on my other Ubuntu 20.04 machine. I narrowed the problem down to what I think is a distribution version check in $FF-SOURCE/debian/rules file.

In the $FF-SOURCE/debian/rules file you have: (around line 53)

```
debian/usr.bin.firefox.in:
        if [ '$(DISTRIB_VERSION_MAJOR)$(DISTRIB_VERSION_MINOR)' -ge '1410' ]; then \
                cp $(CURDIR)/debian/usr.bin.firefox.apparmor.14.10 $(CURDIR)/debian/usr.bin.firefox.in ; \
        fi
```

This will never be true because MAJOR and MINOR in mint returns (in my case) 202 which is less than 1410, thus causing debuild to fail almost right away because it looks for debian/usr.bin.firefox.in and can't find it.

Perhaps Linux Mint needs to patch that line somehow? If I change 1410 to 202 it compiles fine. Or maybe a different solution is needed.

My workflow (Mint 20.2 Cinnamon):

```
apt build-dep firefox
apt source firefox
cd $FF-SOURCE
debuild -i -uc -us -b
```

Firefox source pulled by apt source: firefox_92.0+linuxmint1+uma.tar.xz

Error and some backbuffer:

```
*****************************
* Refreshing debian/control *
*****************************

cp debian/control.in debian/control.tmp
perl debian/build/dump-langpack-control-entries.pl >> debian/control.tmp
sed -e 's/@MOZ_PKG_NAME@/firefox/g' < debian/control.tmp > debian/control
rm -f debian/control.tmp
sed -i -e 's/@MOZ_LOCALE_PKGS@/firefox-locale-af \(= ${binary:Version}\), firefox-locale-an \(= ${binary:Version}\), firefox-locale-ar \(= ${binary:Version}\), firefox-locale-as \(= ${binary:Version}\), firefox-locale-ast \(= ${binary:Version}\), firefox-locale-az \(= ${binary:Version}\), firefox-locale-be \(= ${binary:Version}\), firefox-locale-bg \(= ${binary:Version}\), firefox-locale-bn \(= ${binary:Version}\), firefox-locale-br \(= ${binary:Version}\), firefox-locale-bs \(= ${binary:Version}\), firefox-locale-ca \(= ${binary:Version}\), firefox-locale-cak \(= ${binary:Version}\), firefox-locale-cs \(= ${binary:Version}\), firefox-locale-csb \(= ${binary:Version}\), firefox-locale-cy \(= ${binary:Version}\), firefox-locale-da \(= ${binary:Version}\), firefox-locale-de \(= ${binary:Version}\), firefox-locale-el \(= ${binary:Version}\), firefox-locale-en \(= ${binary:Version}\), firefox-locale-eo \(= ${binary:Version}\), firefox-locale-es \(= ${binary:Version}\), firefox-locale-et \(= ${binary:Version}\), firefox-locale-eu \(= ${binary:Version}\), firefox-locale-fa \(= ${binary:Version}\), firefox-locale-fi \(= ${binary:Version}\), firefox-locale-fr \(= ${binary:Version}\), firefox-locale-fy \(= ${binary:Version}\), firefox-locale-ga \(= ${binary:Version}\), firefox-locale-gd \(= ${binary:Version}\), firefox-locale-gl \(= ${binary:Version}\), firefox-locale-gn \(= ${binary:Version}\), firefox-locale-gu \(= ${binary:Version}\), firefox-locale-he \(= ${binary:Version}\), firefox-locale-hi \(= ${binary:Version}\), firefox-locale-hr \(= ${binary:Version}\), firefox-locale-hsb \(= ${binary:Version}\), firefox-locale-hu \(= ${binary:Version}\), firefox-locale-hy \(= ${binary:Version}\), firefox-locale-ia \(= ${binary:Version}\), firefox-locale-id \(= ${binary:Version}\), firefox-locale-is \(= ${binary:Version}\), firefox-locale-it \(= ${binary:Version}\), firefox-locale-ja \(= ${binary:Version}\), firefox-locale-ka \(= ${binary:Version}\), firefox-locale-kab \(= ${binary:Version}\), firefox-locale-kk \(= ${binary:Version}\), firefox-locale-km \(= ${binary:Version}\), firefox-locale-kn \(= ${binary:Version}\), firefox-locale-ko \(= ${binary:Version}\), firefox-locale-ku \(= ${binary:Version}\), firefox-locale-lg \(= ${binary:Version}\), firefox-locale-lt \(= ${binary:Version}\), firefox-locale-lv \(= ${binary:Version}\), firefox-locale-mai \(= ${binary:Version}\), firefox-locale-mk \(= ${binary:Version}\), firefox-locale-ml \(= ${binary:Version}\), firefox-locale-mn \(= ${binary:Version}\), firefox-locale-mr \(= ${binary:Version}\), firefox-locale-ms \(= ${binary:Version}\), firefox-locale-my \(= ${binary:Version}\), firefox-locale-nb \(= ${binary:Version}\), firefox-locale-ne \(= ${binary:Version}\), firefox-locale-nl \(= ${binary:Version}\), firefox-locale-nn \(= ${binary:Version}\), firefox-locale-nso \(= ${binary:Version}\), firefox-locale-oc \(= ${binary:Version}\), firefox-locale-or \(= ${binary:Version}\), firefox-locale-pa \(= ${binary:Version}\), firefox-locale-pl \(= ${binary:Version}\), firefox-locale-pt \(= ${binary:Version}\), firefox-locale-ro \(= ${binary:Version}\), firefox-locale-ru \(= ${binary:Version}\), firefox-locale-si \(= ${binary:Version}\), firefox-locale-sk \(= ${binary:Version}\), firefox-locale-sl \(= ${binary:Version}\), firefox-locale-sq \(= ${binary:Version}\), firefox-locale-sr \(= ${binary:Version}\), firefox-locale-sv \(= ${binary:Version}\), firefox-locale-sw \(= ${binary:Version}\), firefox-locale-szl \(= ${binary:Version}\), firefox-locale-ta \(= ${binary:Version}\), firefox-locale-te \(= ${binary:Version}\), firefox-locale-th \(= ${binary:Version}\), firefox-locale-tr \(= ${binary:Version}\), firefox-locale-uk \(= ${binary:Version}\), firefox-locale-ur \(= ${binary:Version}\), firefox-locale-uz \(= ${binary:Version}\), firefox-locale-vi \(= ${binary:Version}\), firefox-locale-xh \(= ${binary:Version}\), firefox-locale-zh-hans \(= ${binary:Version}\), firefox-locale-zh-hant \(= ${binary:Version}\), firefox-locale-zu \(= ${binary:Version}\),/' debian/control
test -x debian/rules
mkdir -p "."
CDBS WARNING:    DEB_DH_STRIP_ARGS is deprecated since 0.4.85
cp debian/config/locales.shipped debian/config/locales.shipped.old
if [ '202' -ge '1410' ]; then \
        cp /root/firefox-92.0+linuxmint1+uma/debian/usr.bin.firefox.apparmor.14.10 /root/firefox-92.0+linuxmint1+uma/debian/usr.bin.firefox.in ; \
fi
PYTHONDONTWRITEBYTECODE=1 python3 /root/firefox-92.0+linuxmint1+uma/debian/build/Preprocessor.py -Fsubstitution --marker="%%" -DMOZ_LIBDIR="usr/lib/firefox" -DMOZ_APP_NAME="firefox" -DMOZ_BUILDID="20210903235534" -DMOZ_INCDIR="usr/include/firefox" -DMOZ_IDLDIR="usr/share/idl/firefox" -DMOZ_VERSION="92.0" -DDEB_HOST_ARCH="amd64" -DMOZ_DISPLAY_NAME="Firefox" -DMOZ_PKG_NAME="firefox" -DDISTRIB="Linuxmint" -DMOZ_BRANDING_OPTION="--enable-official-branding" -DTOPSRCDIR="/root/firefox-92.0+linuxmint1+uma" -DDEB_HOST_GNU_TYPE="x86_64-linux-gnu" -DMOZ_ADDONDIR="usr/lib/firefox-addons" -DMOZ_SDKDIR="usr/lib/firefox-devel" -DMOZ_DISTDIR="./obj-x86_64-linux-gnu/dist" -DMOZ_UPDATE_CHANNEL="release" -DMOZ_OBJDIR="./obj-x86_64-linux-gnu" -DDEB_BUILDDIR="." -DMOZ_PYTHON="/root/firefox-92.0+linuxmint1+uma/./obj-x86_64-linux-gnu/_virtualenv/bin/python3" -DDEB_BUILD_ARCH_BITS=64 -DMOZ_DEFAULT_APP_NAME="firefox" -DDISTRIB_VERSION="202" -DDEB_LLVM_VERSION="12" -DMOZ_OFFICIAL_BRANDING -DDEB_PARALLEL_JOBS=20 /root/firefox-92.0+linuxmint1+uma/debian/config/mozconfig.in > /root/firefox-92.0+linuxmint1+uma/debian/config/mozconfig
/root/firefox-92.0+linuxmint1+uma/debian/build/Preprocessor.py:404: DeprecationWarning: 'U' mode is deprecated
  args = open(args, 'rU')
PYTHONDONTWRITEBYTECODE=1 python3 /root/firefox-92.0+linuxmint1+uma/debian/build/Preprocessor.py -Fsubstitution --marker="%%" -DMOZ_LIBDIR="usr/lib/firefox" -DMOZ_APP_NAME="firefox" -DMOZ_BUILDID="20210903235534" -DMOZ_INCDIR="usr/include/firefox" -DMOZ_IDLDIR="usr/share/idl/firefox" -DMOZ_VERSION="92.0" -DDEB_HOST_ARCH="amd64" -DMOZ_DISPLAY_NAME="Firefox" -DMOZ_PKG_NAME="firefox" -DDISTRIB="Linuxmint" -DMOZ_BRANDING_OPTION="--enable-official-branding" -DTOPSRCDIR="/root/firefox-92.0+linuxmint1+uma" -DDEB_HOST_GNU_TYPE="x86_64-linux-gnu" -DMOZ_ADDONDIR="usr/lib/firefox-addons" -DMOZ_SDKDIR="usr/lib/firefox-devel" -DMOZ_DISTDIR="./obj-x86_64-linux-gnu/dist" -DMOZ_UPDATE_CHANNEL="release" -DMOZ_OBJDIR="./obj-x86_64-linux-gnu" -DDEB_BUILDDIR="." -DMOZ_PYTHON="/root/firefox-92.0+linuxmint1+uma/./obj-x86_64-linux-gnu/_virtualenv/bin/python3" -DDEB_BUILD_ARCH_BITS=64 -DMOZ_DEFAULT_APP_NAME="firefox" -DDISTRIB_VERSION="202" -DDEB_LLVM_VERSION="12" -DMOZ_OFFICIAL_BRANDING -DDEB_PARALLEL_JOBS=20 /root/firefox-92.0+linuxmint1+uma/debian/usr.bin.firefox.in > /root/firefox-92.0+linuxmint1+uma/debian/usr.bin.firefox
/root/firefox-92.0+linuxmint1+uma/debian/build/Preprocessor.py:404: DeprecationWarning: 'U' mode is deprecated
  args = open(args, 'rU')
Traceback (most recent call last):
  File "/root/firefox-92.0+linuxmint1+uma/debian/build/Preprocessor.py", line 404, in do_include
    args = open(args, 'rU')
FileNotFoundError: [Errno 2] No such file or directory: '/root/firefox-92.0+linuxmint1+uma/debian/usr.bin.firefox.in'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/firefox-92.0+linuxmint1+uma/debian/build/Preprocessor.py", line 455, in <module>
    main()
  File "/root/firefox-92.0+linuxmint1+uma/debian/build/Preprocessor.py", line 440, in main
    pp.handleCommandLine(None, True)
  File "/root/firefox-92.0+linuxmint1+uma/debian/build/Preprocessor.py", line 142, in handleCommandLine
    self.do_include(f, False)
  File "/root/firefox-92.0+linuxmint1+uma/debian/build/Preprocessor.py", line 408, in do_include
    raise Preprocessor.Error(self, 'FILE_NOT_FOUND', str(args))
__main__.Error: ('', 0, 'FILE_NOT_FOUND', '/root/firefox-92.0+linuxmint1+uma/debian/usr.bin.firefox.in')
make: *** [/root/firefox-92.0+linuxmint1+uma/debian/build/rules.mk:196: debian/usr.bin.firefox] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -b failed
```

**Comment by clefebvre** [comment]
It's built on a build server which runs Ubuntu. I'll close this issue since the packaging is done upstream from us and going forward we'll move away from it entirely.
