### ISSUE TITLE
apt update in Mint 19.3 reports an error

### ISSUE THREAD

**Issue by PSLLSP** [linuxmint/linuxmint#643]
Linux Mint 19.3 amd64

`apt update` started to report an error.

```
root@mint:~# cat /etc/issue
Linux Mint 19.3 Tricia \n \l
```
```
root@mint:~# apt update
Hit:1 http://archive.canonical.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                                        
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease                              
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                
Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease        
Ign:6 http://packages.linuxmint.com tricia InRelease                     
Hit:7 http://packages.linuxmint.com tricia Release 
Traceback (most recent call last):                
  File "/usr/lib/cnf-update-db", line 8, in <module>
    from CommandNotFound.db.creator import DbCreator
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 11, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code
```
I know I should update to newer version of Linux Mint... ;-) This is a headless server, reliable one, it has some older programs and migration to newer version of Linux will require some work, so migration is on my TODO list for a long time..

**Comment by clefebvre** [comment]
It looks like a python issue.

https://stackoverflow.com/questions/56218562/how-to-fix-modulenotfounderror-no-module-named-apt-pkg

**Comment by PSLLSP** [comment]
```
user@mint:~$ python3 -V
Python 3.7.5
```

This command doesn't fix the issue:
```
root@mint:~# apt install --reinstall python3-apt
```

I switched back to python 3.6 and the issue is fixed. It is possible I tried to update python to 3.7 in the past and there was a hidden side effect, that `apt update` was affected... I am not sure what is the default python3 version for Mint 19.3, it could be 3.6 (this is shown by `apt show python3`). 

```
root@mint:~# update-alternatives --config python3
There are 2 choices for the alternative python3 (providing /usr/bin/python3).

  Selection    Path                Priority   Status
------------------------------------------------------------
  0            /usr/bin/python3.7   2         auto mode
  1            /usr/bin/python3.6   1         manual mode
* 2            /usr/bin/python3.7   2         manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
update-alternatives: using /usr/bin/python3.6 to provide /usr/bin/python3 (python3) in manual mode

root@mint:~# python3 -V
Python 3.6.9

root@mint:~# apt update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                 
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                               
Hit:4 http://archive.canonical.com/ubuntu bionic InRelease                                                      
Ign:5 http://packages.linuxmint.com tricia InRelease                                          
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease       
Hit:7 http://packages.linuxmint.com tricia Release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```
