### ISSUE TITLE
flatpak brokes after using flatpak apps in wayland session

### ISSUE THREAD

**Issue by nrv9999** [linuxmint/linuxmint#675]
flatpak brokes after using flatpak apps in wayland session.

working flatpak apps -> use wayland session -> use flatpak app into them -> all flatpak apps can't launch into X (cinnamon default) session.

rebooting system not help, reinstalling app also.

founded in net workarounds:
- delete wayland socket file in XDG_DIR (not exists)
- launching with --nosocket wayland
not working for me.

logs

flatseal (Gtk):
```run --branch=stable --arch=x86_64 --command=com.github.tchx84.Flatseal com.github.tchx84.Flatseal

** (process:11119): WARNING **: 23:40:31.866: Error writing credentials to socket: Произошла ошибка при отправлении сообщения : Обрыв канала (translation: Error occured on message send: pipe break)

(com.github.tchx84.Flatseal:2): Gtk-WARNING **: 23:40:32.133: Failed to open display
```

telegram (Qt):
```/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=telegram-desktop --file-forwarding org.telegram.desktop -- @@u %u @@
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, vkkhrdisplay, wayland, minimal, offscreen, linuxfb, wayland-egl, xcb, minimalegl, vnc.
```

Sweet Home 3D:
```/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/SweetHome3D --file-forwarding com.sweethome3d.Sweethome3d @@ %F @@
Gtk-Message: 23:55:43.672: Failed to load module "xapp-gtk3-module"

(get-scale:6): Gtk-WARNING **: 23:55:43.672: cannot open display: 
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:284)
	at com.eteks.sweethome3d.swing.SwingTools.showSplashScreenWindow(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.init(Unknown Source)
	at com.eteks.sweethome3d.SweetHome3D.main(Unknown Source)
```

**Comment by nrv9999** [comment]
--socket=fallback-x11 workaround works
